#!/usr/bin/env python3

import sys
from datetime import datetime

from app.app import App


def main(name):
    # You can use `input('> ')` to get the user input
    # You can use `print()` to print values in the console
    date = datetime.now()
    app = App(name, date)

    app.show_greeting_message()

    while True:
        user_input = app.ask_for_input()
        app.print_reversed(user_input)
        app.show_palindrome_message_if_needed(user_input)


if __name__ == '__main__':
    main(sys.argv[1])
