#!/usr/bin/env python3

import sys
from datetime import datetime

from app.app import App


def main(name):
    # You can use `input('> ')` to get the user input
    # You can use `print()` to print values in the console
    date = datetime.now()
    app = App(name, date)

    app.start()

    while app.is_running():
        user_input = input('> ')
        app.handle_message(user_input)


if __name__ == '__main__':
    main(sys.argv[1])
